// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xojaodjwmzaaobcwlyrj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhvamFvZGp3bXphYW9iY3dseXJqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAzMDY3MDYsImV4cCI6MjA2NTg4MjcwNn0.CCoSFz4a8q3yq4RyEutVCrVAB2C0_5ajfrtGynQsQ3Q";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);